
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file.html#appspec-reference-lambda
version: 0.0
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-resources.html#reference-appspec-file-structure-resources-lambda
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "codebuild-codedeploy-lambda"
        Alias: "codebuild-codedeploy-lambda"
        CurrentVersion: "1"
        TargetVersion: "2"
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-lambda
Hooks:
  - BeforeAllowTraffic: "<SanityTestHookLambdaFunctionName>"
  - AfterAllowTraffic: "<ValidationTestHookLambdaFunctionName>"
