
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - python -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install-test

  build:
    commands:
      - make test

artifacts:
  files:
    - lambda_function.py
    - appspec.yml
  name: cice-codepipeline-codedeploy-lambda-$(date +%Y-%m-%d)
  